name: Build Resume
on: [push]
jobs:
  build:
    runs-on: shell
    steps:
      - name: Checkout
        run: |
          echo ${{ github.server_url }}
          echo ${{ github.repository }}
          git clone --branch ${{ github.ref_name }} ${{ github.server_url }}/${{ github.repository }}.git .
      # - name: Build
      #   run: docker run --rm -w /doc -v $PWD:/doc thomasweise/docker-texlive-full make
      - name: Build
        run: docker run --rm -w /doc -v $PWD:/doc thomasweise/docker-texlive-full bash /doc/build.sh
      # - name: Rename PDFs
      #   run: |
      #     cp examples/resume_jm_tremblay_*.pdf examples/resume_jm_tremblay_latest.pdf
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: resume
          path: examples/resume_jm_tremblay*.pdf
      - name: Deploy
        run: |
          echo "${{ secrets.FORGEJO_SSH }}" > /tmp/deploy_key
          chmod 600 /tmp/deploy_key
          scp -i /tmp/deploy_key -o StrictHostKeyChecking=no examples/resume_jm_tremblay_*.pdf ${{ vars.JMOPINES_USER }}@${{ vars.JMOPINES_IP }}:/var/www/jmopines/resume/
          rm /tmp/deploy_key